######################################################################
# Automatically generated by qmake (2.01a) Wed Jul 2 14:50:56 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += filereader.h
SOURCES += filereader.cpp main.cpp
