######################################################################
# Automatically generated by qmake (2.01a) Thu Sep 4 15:50:09 2008
######################################################################

CONFIG+=x86_64

OBJECTIVE_SOURCES += main.mm
LIBS += -framework Cocoa -framework Carbon
